---
- name: Install Docker
  hosts: servers
  become: true

  tasks:
    - name: Download Docker installation script
      get_url:
        url: "https://get.docker.com/"
        dest: "/tmp/install_docker.sh"
        mode: "0755"

    - name: Run Docker installation script
      command: "/tmp/install_docker.sh"
      args:
        creates: "/usr/bin/docker"
      register: docker_install_result
      changed_when: "'install' in docker_install_result.stdout"

    - name: Add user to the docker group
      user:
        name: "ansible"
        groups: docker
        append: yes
      changed_when: false
